/**
 * C-25 diploma curriculum (DTE Karnataka, effect from AY 2025-26).
 * Subjects from official scheme-of-studies PDFs (CE / CSE / ECE / ME).
 * Sem 5 pathway electives listed as choose-one style options where available.
 */

import type { BranchCode, CurriculumSubject } from "./curriculum-c20"

function s(
  semester: number,
  code: string,
  name: string,
  extra: Partial<CurriculumSubject> = {},
): CurriculumSubject {
  return { code, name, semester, pathway: null, ...extra }
}

export const C25_BY_BRANCH: Record<BranchCode, CurriculumSubject[]> = {
  CE: [
    s(1, "25SC11I", "Engineering Mathematics-I", { year1_only: true }),
    s(1, "25EG01I", "Essential English Communication", { year1_only: true }),
    s(1, "25CS01I", "IT Skills", { year1_only: true }),
    s(1, "25CE11I", "Construction Materials", { year1_only: true }),
    s(1, "25CE12T", "Environmental Sustainability", { year1_only: true, is_audit: true }),
    s(2, "25SC21I", "Engineering Mathematics-II", { year1_only: true }),
    s(2, "25EE01I", "Fundamentals of Electrical & Electronics Engineering", { year1_only: true }),
    s(2, "25CE21I", "Civil Engineering Graphics and CAD", { year1_only: true }),
    s(2, "25CE22I", "Basic Surveying", { year1_only: true }),
    s(2, "25CE23T", "Indian Constitution", { year1_only: true, is_audit: true }),
    s(3, "25CE31I", "Advanced Surveying"),
    s(3, "25CE32I", "Construction Techniques"),
    s(3, "25CE33I", "Engineering Mechanic and Strength of Materials"),
    s(3, "25CE34I", "Building Planning & Drawing"),
    s(3, "25KA31T", "Sahitya Sinchana-I / Balake Kannada-I", { is_audit: true }),
    s(4, "25CE41I", "Estimation, Costing and Valuation"),
    s(4, "25CE42I", "Hydraulics and Water Resources Engineering"),
    s(4, "25CE43I", "Concrete Technology"),
    s(4, "25CE44I", "Design and Detailing of RC Structures"),
    s(4, "25KA41T", "Sahitya Sinchana-II / Balake Kannada-II", { is_audit: true }),
    s(5, "25CE54I", "Construction Management and Entrepreneurship"),
    s(5, "25CE51IA", "Transportation Engineering", { pathway: "specialization" }),
    s(5, "25CE52IA", "Design and Detailing of Steel Structures", { pathway: "specialization" }),
    s(5, "25CE53IA", "Environmental Engineering", { pathway: "specialization" }),
    s(5, "25CE51IB", "Town Planning & Sustainability", { pathway: "specialization" }),
    s(5, "25CE52IB", "Analysis of Structures", { pathway: "specialization" }),
    s(5, "25CE53IB", "Mechanical Electrical and Plumbing (MEP)", { pathway: "specialization" }),
    s(5, "25CE51IC", "Building Maintenance and Repairs", { pathway: "specialization" }),
    s(5, "25CE52IC", "Geotechnical Engineering", { pathway: "specialization" }),
    s(5, "25CE53IC", "3D Virtual Presentation Techniques", { pathway: "specialization" }),
    s(6, "25CE61I", "Internship/Capstone Project"),
  ],
  CSE: [
    s(1, "25SC11I", "Engineering Mathematics-I", { year1_only: true }),
    s(1, "25CS01I", "IT Skills", { year1_only: true }),
    s(1, "25EE01I", "Fundamentals of Electrical & Electronics Engineering", { year1_only: true }),
    s(1, "25CS11I", "Basics of Digital Logic and Computer Organization", { year1_only: true }),
    s(1, "25CS12T", "Environmental Sustainability", { year1_only: true, is_audit: true }),
    s(2, "25SC21I", "Engineering Mathematics-II", { year1_only: true }),
    s(2, "25EG01I", "Essential English Communication", { year1_only: true }),
    s(2, "25ME02I", "Computer Aided Engineering Graphics", { year1_only: true }),
    s(2, "25CS21I", "Thinking Programming with Python", { year1_only: true }),
    s(2, "25CS22T", "Indian Constitution", { year1_only: true, is_audit: true }),
    s(3, "25CS31I", "Database Concepts & Technologies"),
    s(3, "25CS32I", "Computer Networks"),
    s(3, "25CS33I", "Data Structures with Python"),
    s(3, "25CS34I", "System and Network Administration"),
    s(3, "25KA31T", "Sahitya Sinchana-I / Balake Kannada-I", { is_audit: true }),
    s(4, "25CS41I", "Operating Systems and Administration"),
    s(4, "25CS42I", "Object Oriented Programming with Java"),
    s(4, "25CS43I", "Data Analysis and Algorithm Design"),
    s(4, "25CS44I", "Web Development"),
    s(4, "25KA41T", "Sahitya Sinchana-II / Balake Kannada-II", { is_audit: true }),
    s(5, "25EC54I", "Software Engineering and Entrepreneurship"),
    s(5, "25CS51IA", "Artificial Intelligence Concepts", { pathway: "specialization" }),
    s(5, "25CS52IA", "Machine Learning for AI", { pathway: "specialization" }),
    s(5, "25CS53IA", "Deep Learning Techniques", { pathway: "specialization" }),
    s(5, "25CS51IB", "Cloud Computing Architecture", { pathway: "specialization" }),
    s(5, "25CS52IB", "Cloud Networking", { pathway: "specialization" }),
    s(5, "25CS53IB", "Cloud Security and Compliance", { pathway: "specialization" }),
    s(5, "25CS51IC", "Backend Development using Web services", { pathway: "specialization" }),
    s(5, "25CS52IC", "Frontend Development", { pathway: "specialization" }),
    s(5, "25CS53IC", "Integration and Deployment", { pathway: "specialization" }),
    s(5, "25CS51ID", "Cyber-Physical System", { pathway: "specialization" }),
    s(5, "25CS52ID", "Cyber Security", { pathway: "specialization" }),
    s(5, "25CS53ID", "Ethical Hacking", { pathway: "specialization" }),
    s(6, "25CS61I", "Internship/Capstone Project"),
  ],
  ECE: [
    s(1, "25SC11I", "Engineering Mathematics-I", { year1_only: true }),
    s(1, "25CS01I", "IT Skills", { year1_only: true }),
    s(1, "25EE01I", "Fundamentals of Electrical & Electronics Engineering", { year1_only: true }),
    s(1, "25EC11I", "Digital Electronics-1", { year1_only: true }),
    s(1, "25EC12I", "Environmental Sustainability", { year1_only: true }),
    s(2, "25SC21I", "Engineering Mathematics-II", { year1_only: true }),
    s(2, "25EG01I", "Essential English Communication", { year1_only: true }),
    s(2, "25ME02I", "Computer Aided Engineering Graphics", { year1_only: true }),
    s(2, "25EC21I", "Applied Electronics-1", { year1_only: true }),
    s(2, "25EC22T", "Indian Constitution", { year1_only: true, is_audit: true }),
    s(3, "25EC31I", "Digital Electronics - II"),
    s(3, "25EC32I", "Communication systems"),
    s(3, "25EC33I", "Applied Electronics -II"),
    s(3, "25EC34I", "C - Programming"),
    s(3, "25KA31T", "Sahitya Sinchana-I / Balake Kannada-I", { is_audit: true }),
    s(4, "25EC41I", "Power Electronics"),
    s(4, "25EC42I", "Electronic Measurements and Analysis"),
    s(4, "25EC43I", "Microcontroller and Applications"),
    s(4, "25EC44I", "Verilog Programming for Digital Circuits"),
    s(5, "25EC54I", "Project Management and Entrepreneurship"),
    s(5, "25EC51IA", "Industrial Automation", { pathway: "specialization" }),
    s(5, "25EC52IA", "Sensors & Actuators", { pathway: "specialization" }),
    s(5, "25EC53IA", "Automation & Robotics", { pathway: "specialization" }),
    s(5, "25EC51IB", "Networking Systems", { pathway: "specialization" }),
    s(5, "25EC52IB", "Industrial Internet of things [IIoT]", { pathway: "specialization" }),
    s(5, "25EC53IB", "Agritech", { pathway: "specialization" }),
    s(5, "25EC51IC", "Embedded Technology", { pathway: "specialization" }),
    s(5, "25EC52IC", "Integrated Communication Technologies", { pathway: "specialization" }),
    s(5, "25EC53IC", "Electric vehicles & Drone Technologies", { pathway: "specialization" }),
    s(6, "25EC61I", "Internship/Capstone Project"),
  ],
  ME: [
    s(1, "25SC11I", "Engineering Mathematics-I", { year1_only: true }),
    s(1, "25EG01I", "Essential English Communication", { year1_only: true }),
    s(1, "25ME01I", "Computer Aided Engineering Drawing", { year1_only: true }),
    s(1, "25ME11I", "Mechanical Engineering Practices-I", { year1_only: true }),
    s(1, "25ME12T", "Environmental Sustainability", { year1_only: true, is_audit: true }),
    s(2, "25SC21I", "Engineering Mathematics-II", { year1_only: true }),
    s(2, "25CS01I", "IT Skills", { year1_only: true }),
    s(2, "25EE01I", "Fundamentals of Electrical & Electronics Engineering", { year1_only: true }),
    s(2, "25ME21I", "Mechanical Engineering Practices-II", { year1_only: true }),
    s(2, "25ME22T", "Indian Constitution", { year1_only: true, is_audit: true }),
    s(3, "25ME31I", "Mechanics of Materials"),
    s(3, "25ME32I", "Thermal Engineering"),
    s(3, "25ME33I", "Fluid Power Engineering"),
    s(3, "25ME34I", "Programming Concepts in Mechanical Engineering"),
    s(3, "25KA31T", "Sahitya Sinchana-I / Balake Kannada-I", { is_audit: true }),
    s(4, "25ME41I", "Product design, Drawing and development"),
    s(4, "25ME42I", "Operations management"),
    s(4, "25ME43I", "Machine Tool Technology & CNC Programming"),
    s(4, "25ME44I", "Elements of Industrial Automation"),
  ],
}

